name: the-build
type: profile
description: 'Base install from palantirnet/the-build.'
core: 8.x
install:
  # Core modules
  - block
  - block_content
  - breakpoint
  - ckeditor
  - color
  - config
  - contextual
  - datetime
  - dblog
  - dynamic_page_cache
  - editor
  - field_ui
  - file
  - help
  - image
  - menu_link_content
  - menu_ui
  - node
  - options
  - page_cache
  - path
  - rdf
  - shortcut
  - taxonomy
  - toolbar
  - views
  - views_ui
  # Contrib modules
  - config_split
  - workbench
  - workbench_tabs
themes:
  - bartik
  - seven
