# These properties are for running the Drupal Skeleton on circle.
drupal:
  root: web
  sites:
    default:
      dir: default
      uri: http://drupal-skeleton.local
      hash_salt: temporary
      profile: standard
      database:
        database: circle_test
        username: ubuntu
        password:
        host: 127.0.0.1
      settings:
        file_public_path: sites/default/files
        file_private_path:
  twig:
    debug: false
