# @file
# Build configuration for the palantirnet/drupal-skeleton project.

build:
  host: other

drupal:
  root: "web"

  twig:
    debug: true

  sites:
    default:
      dir: default
      uri: "drupal-skeleton.local"
      hash_salt: "temporary"
      profile: standard
      database:
        database: "drupal"

    # Multisites created by `phing drupal-add-multisite` will be automatically added here.
    # @multisite_placeholder@

    _defaults:
      database:
        username: "root"
        password: "root"
        host: "127.0.0.1"

behat:
  args: "--suite=default --strict"
